# СЕРВИС ФОРМИРОВАНИЯ ЗАДАЧ ДЛЯ МОСКВИЧЕЙ ПО КОНТРОЛЮ РАБОТ ПОДРЯДЧИКОВ В СФЕРЕ ГОРОДСКОГО БЛАГОУСТРОЙСТВА
## Задача
**Разработка сервиса, который с помощью распознавания документации проектов городского благоустройства сформирует для москвичей задания по мониторингу выполненных подрядчиками работ**

In [1]:
import os
import pandas as pd
import numpy as np

#Для работы с Excel
import xlrd, xlwt
from xlsxwriter.utility import xl_rowcol_to_cell
import openpyxl

pd.set_option('display.max_columns', 500)

Объединяем файлы по справочнику ТСН

In [2]:
# Задать директорию. Проверить доступ к файлам
path = os.getcwd()
path

'd:\\IT\\Hackatones\\Lider_IT_22'

### Локальный вариант: 
    - Доступа к файлам нет. Зададим путь сами.
### Он-лайн сервис:
    - задать пути ссылки.

In [2]:
# Локальный вариант
path = 'D:\IT\Hackatones\Lider_IT_22\ТЗ\СН-ТСН\ТСН-2001'

for dirs,folder,files in os.walk(path):
    print('Выбранный каталог: ', dirs)
    print('Вложенные папки: ', folder)
    print('Файлы в папке: ', files)
    print("\n")
    list_path = []
    for file in files:
        #print('Полный путь к файлу: ', os.path.join(dirs, file))
        list_path.append(os.path.join(dirs, file))
    print(list_path)

Выбранный каталог:  D:\IT\Hackatones\Lider_IT_22\ТЗ\СН-ТСН\ТСН-2001
Вложенные папки:  []
Файлы в папке:  ['10.Временные сооружения МГЭ. Сборник 1.xlsx', '14.Обслуживание оборудования.Сборники 1-19.xlsx', '15.Транспортные.Сборники 1-11.xlsx', '16. Укрупненные.Сборники 1-3,5,6.xlsx', '17. Оформление города.Сборники 1-2.xlsx', '19.НЦКР. Сборники 2-4.xlsx', '20.НЦСМ.Сборники 1,3.xlsx', '3.Строительные.Сборник 1-9.xlsx', '3.Строительные.Сборник 10-19.xlsx', '3.Строительные.Сборник 20-29.xlsx', '3.Строительные.Сборник 30-39.xlsx', '3.Строительные.Сборник 40-45.xlsx', '3.Строительные.Сборник 47. Озеленение, благоустройство, малые формы.xlsx', '3.Строительные.Сборник 51.Прочие строительные работы.xlsx', '4.Монтаж оборудования.Сборники 0,1,3,6-8,10-12,18,21,24,28,29,31,33,34,36,37.xlsx', '5.Пуско-наладочные.Сборники 1-4,6,7,9-11.xlsx', '6.Ремонтно-строит.Сборник 0,51,52-69.xlsx', '7.Реставрационные.Сборники1-31.xlsx', '8.Нормы НР и СП МГЭ.Сборники 1,2.xlsx', '9.Затраты в зим.вр. МГЭ. Сборник 0.xlsx']


['D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\10.Временные сооружения МГЭ. Сборник 1.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\14.Обслуживание оборудования.Сборники 1-19.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\15.Транспортные.Сборники 1-11.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\16. Укрупненные.Сборники 1-3,5,6.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\17. Оформление города.Сборники 1-2.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\19.НЦКР. Сборники 2-4.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\20.НЦСМ.Сборники 1,3.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\3.Строительные.Сборник 1-9.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\3.Строительные.Сборник 10-19.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\3.Строительные.Сборник 20-29.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\3.Строительные.Сборник 30-39.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\3.Строительные.Сборник 40-45.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\3.Строительные.Сборник 47. Озеленение, благоустройство, малые формы.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\3.Строительные.Сборник 51.Прочие строительные работы.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\4.Монтаж оборудования.Сборники 0,1,3,6-8,10-12,18,21,24,28,29,31,33,34,36,37.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\5.Пуско-наладочные.Сборники 1-4,6,7,9-11.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\6.Ремонтно-строит.Сборник 0,51,52-69.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\7.Реставрационные.Сборники1-31.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\8.Нормы НР и СП МГЭ.Сборники 1,2.xlsx', 'D:\\IT\\Hackatones\\Lider_IT_22\\ТЗ\\СН-ТСН\\ТСН-2001\\9.Затраты в зим.вр. МГЭ. Сборник 0.xlsx']

Необходимо объединить справочник, чтобы автоматизировать поиск
- Код у меня считался долго- 7,5 минуты

In [3]:
path = 'D:\IT\Hackatones\Lider_IT_22\ТЗ\СН-ТСН\ТСН-2001'

for dirs,folder,files in os.walk(path):
    print('Выбранный каталог: ', dirs)
    print('Вложенные папки: ', folder)
    print('Файлы в папке: ', files)
    
    path_list = []
    for file in files:
        df = pd.read_excel(os.path.join(dirs, file), na_filter=False, skiprows=25, header=None, index_col=None)
        df = df[~df.isin(df.tail(13))].dropna()
        path_list.append(df)
    data = pd.concat(path_list, ignore_index=True)

Выбранный каталог:  D:\IT\Hackatones\Lider_IT_22\ТЗ\СН-ТСН\ТСН-2001
Вложенные папки:  []
Файлы в папке:  ['10.Временные сооружения МГЭ. Сборник 1.xlsx', '14.Обслуживание оборудования.Сборники 1-19.xlsx', '15.Транспортные.Сборники 1-11.xlsx', '16. Укрупненные.Сборники 1-3,5,6.xlsx', '17. Оформление города.Сборники 1-2.xlsx', '19.НЦКР. Сборники 2-4.xlsx', '20.НЦСМ.Сборники 1,3.xlsx', '3.Строительные.Сборник 1-9.xlsx', '3.Строительные.Сборник 10-19.xlsx', '3.Строительные.Сборник 20-29.xlsx', '3.Строительные.Сборник 30-39.xlsx', '3.Строительные.Сборник 40-45.xlsx', '3.Строительные.Сборник 47. Озеленение, благоустройство, малые формы.xlsx', '3.Строительные.Сборник 51.Прочие строительные работы.xlsx', '4.Монтаж оборудования.Сборники 0,1,3,6-8,10-12,18,21,24,28,29,31,33,34,36,37.xlsx', '5.Пуско-наладочные.Сборники 1-4,6,7,9-11.xlsx', '6.Ремонтно-строит.Сборник 0,51,52-69.xlsx', '7.Реставрационные.Сборники1-31.xlsx', '8.Нормы НР и СП МГЭ.Сборники 1,2.xlsx', '9.Затраты в зим.вр. МГЭ. Сборник 0.xlsx']

In [4]:
data.info()
display(data.head(20))
data.tail(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 532570 entries, 0 to 532569
Data columns (total 30 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   0       532570 non-null  object
 1   1       532570 non-null  object
 2   2       532570 non-null  object
 3   3       532570 non-null  object
 4   4       532570 non-null  object
 5   5       532570 non-null  object
 6   6       532570 non-null  object
 7   7       532570 non-null  object
 8   8       532570 non-null  object
 9   9       532570 non-null  object
 10  10      532570 non-null  object
 11  11      532570 non-null  object
 12  12      532570 non-null  object
 13  13      532570 non-null  object
 14  14      532570 non-null  object
 15  15      532570 non-null  object
 16  16      532570 non-null  object
 17  17      532570 non-null  object
 18  18      532570 non-null  object
 19  19      532570 non-null  object
 20  20      532570 non-null  object
 21  21      532570 non-null  object
 22  22      532570 non-null  object
 23  23      532570 non-null  object
 24  24      532570 non-null  object
 25  25      532570 non-null  object
 26  26      532570 non-null  object
 27  27      395360 non-null  object
 28  28      278865 non-null  object
 29  29      17831 non-null   object
dtypes: object(30)
memory usage: 121.9+ MB

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
0,Раздел 1.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN
1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN
2,1,10.1-1-1,,,Рельсовые подкрановые пути строительных башенн...,,,,,,,1 звено в 2 нитки,,1,,,,,,,,,,,,,,,,NaN
3,,,,,ЗП,,,,,,,,,,,,1358.48,1,,1.047,,1422,,,,26.72,38005,,,NaN
4,,,,,ЭМ,,,,,,,,,,,,4120.07,1,,1.047,,4314,,,,8.85,38176,,,NaN
5,,,,,в т.ч. ЗПМ,,,,,,,,,,,,251.19,1,,1.047,,(263),,,,26.72,(7027),,,NaN
6,,,,,МР,,,,,,,,,,,,7077,1,,1,,7077,,,,15.62,110543,,,NaN
7,,,,,НР от ЗП,,,,,,,%,,105,,,,,,,,1493,,,,87,33064,,,NaN
8,,,,,СП от ЗП,,,,,,,%,,77,,,,,,,,1095,,,,41,15582,,,NaN
9,,,,,"НР и СП от ЗПМ (98,00% и 77,00%)",,,,,,,%,,175,,,,,,,,460,,,,160,11243,,,NaN
10,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN
11,,,,,ЗТР,,,,,,,чел-ч,,121.51,,,,1,,1.047,,127,,,,,,,,NaN
12,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN
13,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN
14,,,,,,,,,,,,,,,,,,,,,,15861,,,,,246613,,,NaN
15,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN
16,2,10.1-1-2,,,Рельсовые подкрановые пути строительных башенн...,,,,,,,1 звено в 2 нитки,,1,,,,,,,,,,,,,,,,NaN
17,,,,,ЗП,,,,,,,,,,,,1342.34,1,,1.047,,1405,,,,26.72,37553,,,NaN
18,,,,,ЭМ,,,,,,,,,,,,4270.66,1,,1.047,,4471,,,,9.32,41673,,,NaN
19,,,,,в т.ч. ЗПМ,,,,,,,,,,,,344.15,1,,1.047,,(360),,,,26.72,(9628),,,NaN

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
532550,,,,,МР,,,,,,,,,,,,,1.28,,1,1,,1,,,7.88,,10,,NaN
532551,,,,,НР от ЗП,,,,,,,,,%,,,125,,,,,,15,,,103,,336,,NaN
532552,,,,,СП от ЗП,,,,,,,,,%,,,94,,,,,,11,,,46,,150,,NaN
532553,,,,,ЗТР,,,,,,,,,чел-ч,,,0.87,,,1,1.067,,1,,,,,,,NaN
532554,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN
532555,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN
532556,,,,,,,,,,,,,,,,,,,,,,,39,,,,,822,,NaN
532557,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN
532558,6,9.0-1-2,,,"Временное отопление, законченных вчерне жилых,...",,,,,,,,,1000 м3 здания,,,1,,,,,,,,,,,,,NaN
532559,,,,,ЗП,,,,,,,,,,,,,68.09,,1,1.067,,73,,,26.72,,1941,,NaN
532560,,,,,ЭМ,,,,,,,,,,,,,0,,1,1.067,,0,,,0,,0,,NaN
532561,,,,,в т.ч. ЗПМ,,,,,,,,,,,,,0,,1,1.067,,(0),,,26.72,,(0),,NaN
532562,,,,,МР,,,,,,,,,,,,,6.98,,1,1,,7,,,7.88,,55,,NaN
532563,,,,,НР от ЗП,,,,,,,,,%,,,125,,,,,,91,,,103,,1999,,NaN
532564,,,,,СП от ЗП,,,,,,,,,%,,,94,,,,,,69,,,46,,893,,NaN
532565,,,,,ЗТР,,,,,,,,,чел-ч,,,5.16,,,1,1.067,,6,,,,,,,NaN
532566,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN
532567,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN
532568,,,,,,,,,,,,,,,,,,,,,,,240,,,,,4888,,NaN
532569,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN

Сохраняет тоже долго. Зато весит справочник в 3 раза легче всех отдельных файлов.

data.to_excel('TCH_2001.xlsx')

## Почистим справочник. 
**Оставим:**
- код-шифр, 
- наименование работ, 
- единицы и 
- стоимость общую

In [6]:
# Проверим в каких столбцах нет данных
data[2].unique()

array([''], dtype=object)

In [5]:
# Удалим пустые и не нужные столбцы 
ch = data.drop({2, 3, 5, 6, 7, 8, 28, 29}, axis=1)
ch

,0,1,4,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27
0,Раздел 1.,,,,,,,,,,,,,,,,,,,,,
1,,,,,,,,,,,,,,,,,,,,,,
2,1,10.1-1-1,Рельсовые подкрановые пути строительных башенн...,,,1 звено в 2 нитки,,1,,,,,,,,,,,,,,
3,,,ЗП,,,,,,,,1358.48,1,,1.047,,1422,,,,26.72,38005,
4,,,ЭМ,,,,,,,,4120.07,1,,1.047,,4314,,,,8.85,38176,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532565,,,ЗТР,,,,,чел-ч,,,5.16,,,1,1.067,,6,,,,,
532566,,,,,,,,,,,,,,,,,,,,,,
532567,,,,,,,,,,,,,,,,,,,,,,
532568,,,,,,,,,,,,,,,,,240,,,,,4888
532569,,,,,,,,,,,,,,,,,,,,,,

Поработаем с наименованиями работ. Уберем дополнительные пункты.

In [6]:
data1 = ch[4].value_counts().reset_index()
data1

                                                   index       4
0                                                         202917
1                                                     ЗП   39164
2                                                    ЗТР   39084
3                                               НР от ЗП   38348
4                                               СП от ЗП   38348
...                                                  ...     ...
43476  Установка арматурных изделий, отдельных стержн...       1
43477  Установка закладных деталей монолитных железоб...       1
43478  Бетонирование по схеме "кран-бадья" монолитных...       1
43479  Бетонирование по схеме "кран-бадья" монолитных...       1
43480  Временное отопление, законченных вчерне жилых,...       1

[43481 rows x 2 columns]

In [7]:
data1 = data1[(data1[4] < 5)]
data1

                                                   index  4
16     Проходка коллекторов щитовым способом в нормал...  3
17     Проходка коллекторов щитовым способом в сложны...  3
18     Проходка коллекторов щитовым способом в сложны...  3
19     Проходка коллекторов щитовым способом в сложны...  3
20     Проходка коллекторов щитовым способом в сложны...  3
...                                                  ... ..
43476  Установка арматурных изделий, отдельных стержн...  1
43477  Установка закладных деталей монолитных железоб...  1
43478  Бетонирование по схеме "кран-бадья" монолитных...  1
43479  Бетонирование по схеме "кран-бадья" монолитных...  1
43480  Временное отопление, законченных вчерне жилых,...  1

[43465 rows x 2 columns]

In [8]:
list_work = list(data1['index'])
list_work.append('')
#list_work

In [30]:
df = (
    ch[ch[4].isin(list_work)]
    .reset_index(drop=True)
    #.drop(columns={'index'})
)
display(df.head(10))
df.tail(10)

,0,1,4,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27
0,Раздел 1.,,,,,,,,,,,,,,,,,,,,,
1,,,,,,,,,,,,,,,,,,,,,,
2,1,10.1-1-1,Рельсовые подкрановые пути строительных башенн...,,,1 звено в 2 нитки,,1,,,,,,,,,,,,,,
3,,,,,,,,,,,,,,,,,,,,,,
4,,,,,,,,,,,,,,,,,,,,,,
5,,,,,,,,,,,,,,,,,,,,,,
6,,,,,,,,,,,,,,,,15861,,,,,246613,
7,,,,,,,,,,,,,,,,,,,,,,
8,2,10.1-1-2,Рельсовые подкрановые пути строительных башенн...,,,1 звено в 2 нитки,,1,,,,,,,,,,,,,,
9,,,,,,,,,,,,,,,,,,,,,,

,0,1,4,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27
246929,5,9.0-2-3,"Временное отопление, законченных вчерне произв...",,,,,1000 м3 здания,,,1,,,,,,,,,,,
246930,,,,,,,,,,,,,,,,,,,,,,
246931,,,,,,,,,,,,,,,,,,,,,,
246932,,,,,,,,,,,,,,,,,39,,,,,822
246933,,,,,,,,,,,,,,,,,,,,,,
246934,6,9.0-1-2,"Временное отопление, законченных вчерне жилых,...",,,,,1000 м3 здания,,,1,,,,,,,,,,,
246935,,,,,,,,,,,,,,,,,,,,,,
246936,,,,,,,,,,,,,,,,,,,,,,
246937,,,,,,,,,,,,,,,,,240,,,,,4888
246938,,,,,,,,,,,,,,,,,,,,,,

In [31]:
# Удалим столбцы с нан
df.dropna(axis=1, how='all', inplace=True)

In [32]:
df

,0,1,4,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27
0,Раздел 1.,,,,,,,,,,,,,,,,,,,,,
1,,,,,,,,,,,,,,,,,,,,,,
2,1,10.1-1-1,Рельсовые подкрановые пути строительных башенн...,,,1 звено в 2 нитки,,1,,,,,,,,,,,,,,
3,,,,,,,,,,,,,,,,,,,,,,
4,,,,,,,,,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246934,6,9.0-1-2,"Временное отопление, законченных вчерне жилых,...",,,,,1000 м3 здания,,,1,,,,,,,,,,,
246935,,,,,,,,,,,,,,,,,,,,,,
246936,,,,,,,,,,,,,,,,,,,,,,
246937,,,,,,,,,,,,,,,,,240,,,,,4888
246938,,,,,,,,,,,,,,,,,,,,,,

In [42]:
df.loc[df[9] == 1, 9] = '' 
df.loc[df[10] == 1, 10] = '' 
df.loc[df[11] == 1, 11] = '' 
df.loc[df[12] == 1, 12] = '' 
df.loc[df[13] == 1, 13] = ''

In [43]:

df[913] = df[9].astype(str) + df[10].astype(str) + df[11].astype(str) + df[12].astype(str) + df[13].astype(str)
#df[1419] = df[14].astype(str) + df[15].astype(str) + df[16].astype(str) + df[17].astype(str) +df[18].astype(str) + df[19].astype(str)
#df[2023] = df[20].astype(str) + df[21].astype(str) + df[22].astype(str) + df[23].astype(str)

# Уберем Nan на пропуски
df[24] = df[24].replace(np.nan, '')
df[25] = df[25].replace(np.nan, '')
df[26] = df[26].replace(np.nan, '')
df[27] = df[27].replace(np.nan, '')
df[2427] = df[24].astype(str) + df[25].astype(str) + df[26].astype(str) + df[27].astype(str)

In [44]:
df_final = df.drop(columns={0,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27})
df_final.info()
df_final

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246939 entries, 0 to 246938
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   1       246939 non-null  object
 1   4       246939 non-null  object
 2   913     246939 non-null  object
 3   2427    246939 non-null  object
dtypes: object(4)
memory usage: 7.5+ MB

,1,4,913,2427
0,,,,
1,,,,
2,10.1-1-1,Рельсовые подкрановые пути строительных башенн...,1 звено в 2 нитки,
3,,,,
4,,,,
...,...,...,...,...
246934,9.0-1-2,"Временное отопление, законченных вчерне жилых,...",1000 м3 здания,
246935,,,,
246936,,,,
246937,,,,4888
246938,,,,

In [45]:
# Переименуем столбцы
df_final = (
    df_final
    .rename(columns={1:'code', 4:'work', 913:'count', 2427:'total'})
   # .query('count != "чел-ч"')
)
df_final = df_final[~(df_final['code'] == "") | ~(df_final['total'] == "")]

# Преобразуем типы
df_final['total'] = df_final['total'].replace('', np.nan).fillna(0).astype('float')

df_final.info()
df_final.head(10)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 87991 entries, 2 to 246937
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    87991 non-null  object
 1   work    87991 non-null  object
 2   count   87991 non-null  object
 3   total   87991 non-null  float64
dtypes: float64(1), object(3)
memory usage: 3.4+ MB

,code,work,count,total
2,10.1-1-1,Рельсовые подкрановые пути строительных башенн...,1 звено в 2 нитки,0.0
6,,,,246613.0
8,10.1-1-2,Рельсовые подкрановые пути строительных башенн...,1 звено в 2 нитки,0.0
12,,,,269158.0
14,10.1-1-3,Рельсовые подкрановые пути строительных башенн...,1 звено в 2 нитки,0.0
18,,,,134601.0
20,10.1-1-4,Рельсовые подкрановые пути строительных башенн...,1 звено в 2 нитки,0.0
24,,,,157893.0
26,10.1-1-5,Рельсовые подкрановые пути строительных башенн...,1 звено в 2 нитки,0.0
30,,,,128099.0

In [47]:
df1 = (
    df_final
    .drop('total', axis=1)
    .reset_index(drop=True)
)
df1.info()
df1.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87991 entries, 0 to 87990
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    87991 non-null  object
 1   work    87991 non-null  object
 2   count   87991 non-null  object
dtypes: object(3)
memory usage: 2.0+ MB

,code,work,count
0,10.1-1-1,Рельсовые подкрановые пути строительных башенн...,1 звено в 2 нитки
1,,,
2,10.1-1-2,Рельсовые подкрановые пути строительных башенн...,1 звено в 2 нитки

In [48]:
df2 = (
    df_final[['total']]
    .reset_index(drop=True)
)
df2.info()
df2.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87991 entries, 0 to 87990
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   total   87991 non-null  float64
dtypes: float64(1)
memory usage: 687.6 KB

      total
0       0.0
1  246613.0
2       0.0

In [49]:
# Добавим строку вниз, а потом удалим первую строку
df2.loc[len(df2.index)] = [0]
df2 = df2.drop(df2.iloc[0]).reset_index(drop=True)
df2.info()
df2.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87991 entries, 0 to 87990
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   total   87991 non-null  float64
dtypes: float64(1)
memory usage: 687.6 KB

      total
0  246613.0
1       0.0
2  269158.0

In [50]:
df_final = (
    df1
    .join(df2, how='left')
    .query('code != ""')
    .reset_index(drop=True)
)
df_final.info()
df_final

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44022 entries, 0 to 44021
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    44022 non-null  object
 1   work    44022 non-null  object
 2   count   44022 non-null  object
 3   total   44022 non-null  float64
dtypes: float64(1), object(3)
memory usage: 1.3+ MB

,code,work,count,total
0,10.1-1-1,Рельсовые подкрановые пути строительных башенн...,1 звено в 2 нитки,246613.0
1,10.1-1-2,Рельсовые подкрановые пути строительных башенн...,1 звено в 2 нитки,269158.0
2,10.1-1-3,Рельсовые подкрановые пути строительных башенн...,1 звено в 2 нитки,134601.0
3,10.1-1-4,Рельсовые подкрановые пути строительных башенн...,1 звено в 2 нитки,157893.0
4,10.1-1-5,Рельсовые подкрановые пути строительных башенн...,1 звено в 2 нитки,128099.0
...,...,...,...,...
44017,9.0-1-3,"Временное отопление, законченных вчерне крупны...",1000 м3 здания,1467.0
44018,9.0-2-1,"Временное отопление, законченных вчерне произв...",1000 м3 здания,3272.0
44019,9.0-2-2,"Временное отопление, законченных вчерне произв...",1000 м3 здания,1631.0
44020,9.0-2-3,"Временное отопление, законченных вчерне произв...",1000 м3 здания,822.0
44021,9.0-1-2,"Временное отопление, законченных вчерне жилых,...",1000 м3 здания,4888.0

In [51]:
df_final['count'].sort_values().tolist()

['1 АРМ',
 '1 АРМ',
 '1 АРМ',
 '1 АРМ',
 '1 АРМ',
 '1 АРМ',
 '1 АРМ',
 '1 АРМ',
 '1 АРМ',
 '1 БД',
 '1 БД',
 '1 БД',
 '1 БП',
 '1 ГС',
 '1 ГС',
 '1 ДРС',
 '1 ДРС',
 '1 ДТ',
 '1 ДТ',
 '1 ДТ',
 '1 ДТ',
 '1 ДТ',
 '1 ИБС',
 '1 ИБС',
 '1 ИБС',
 '1 ЛВС',
 '1 МПД',
 '1 ПНТ',
 '1 ПЭВМ',
 '1 ПЭВМ',
 '1 ПЭВМ',
 '1 ПЭВМ',
 '1 ПЭВМ',
 '1 ПЭВМ',
 '1 ПЭВМ',
 '1 ПЭВМ',
 '1 ПЭВМ',
 '1 ПЭВМ',
 '1 ПЭВМ',
 '1 ПЭВМ',
 '1 ПЭВМ',
 '1 УЗДЛ',
 '1 УЗДЛ',
 '1 УСД',
 '1 ЦТП',
 '1 абонентский отвод',
 '1 автоматический выключатель',
 '1 автоматический выключатель',
 '1 агрегат',
 '1 агрегат',
 '1 агрегат',
 '1 агрегат',
 '1 агрегат',
 '1 агрегат',
 '1 агрегат',
 '1 агрегат',
 '1 агрегат',
 '1 агрегат',
 '1 агрегат',
 '1 агрегат',
 '1 агрегат',
 '1 агрегат',
 '1 активное устройство',
 '1 анализ',
 '1 анализ',
 '1 анализ',
 '1 анализ одного ингредиенты',
 '1 анализ одного ингредиенты',
 '1 анализ одного ингредиенты',
 '1 анализ одного ингредиенты',
 '1 анализ одного ингредиенты',
 '1 анкер',
 '1 анкер',
 '1 анкер',
 '1 анкер',
 '1 антенна',
 '1 антенна',
 '1 антенна',
 '1 антенна',
 '1 антенна',
 '1 антенна',
 '1 антенна',
 '1 антенна',
 '1 антенна',
 '1 антенна',
 '1 антенна',
 '1 антенна',
 '1 антенна',
 '1 антенна',
 '1 аппарат',
 '1 аппарат',
 '1 аппарат',
 '1 аппарат',
 '1 аппаратная',
 '1 байпас',
 '1 байпас',
 '1 байпас',
 '1 байпас',
 '1 байпас',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 бак',
 '1 баланс',
 '1 баланс',
 '1 баланс',
 '1 баланс',
 '1 баланс',
 '1 баланс',
 '1 баланс',
 '1 баланс',
 '1 баланс',
 '1 баланс',
 '1 баланс',
 '1 баланс',
 '1 балка',
 '1 балка',
 '1 балка',
 '1 балка дверей шахты',
 '1 балка дверей шахты',
 '1 балка дверей шахты',
 '1 балка дверей шахты',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка пролетного строения',
 '1 балка противовеса',
 '1 балка противовеса',
 '1 балка противовеса',
 '1 балка противовеса',
 '1 банк',
 '1 барабан',
 '1 башмак',
 '1 бленда',
 '1 бленда',
 '1 бленда',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок',
 '1 блок сигнализации',
 '1 блок сигнализации',
 '1 блок сигнализации',
 '1 бокс',
 '1 бокс',
 '1 бокс',
 '1 бокс',
 '1 бокс',
 '1 бокс',
 '1 бокс',
 '1 боров',
 '1 боров',
 '1 вал',
 '1 вал',
 '1 вал',
 '1 вал',
 '1 вал',
 '1 ввод',
 '1 ввод',
 '1 ввод',
 '1 ввод',
 '1 ввод',
 '1 ввод',
 '1 ввод',
 '1 ввод в забой',
 '1 ввод и вывод щита',
 '1 ввод и вывод щита',
 '1 ввод и вывод щита',
 '1 ввод и вывод щита',
 '1 ввод и вывод щита',
 '1 вводное устройство',
 '1 вводное устройство',
 '1 вводное устройство',
 '1 вводное устройство',
 '1 вентиль',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентилятор',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная сеть',
 '1 вентиляционная установка',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 венткиоск',
 '1 ветвь',
 '1 вкладыш',
 '1 водоподогреватель',
 '1 водоподогреватель',
 '1 водоподогреватель',
 '1 водоподогреватель',
 '1 водоподогреватель',
 '1 водоподогреватель',
 '1 водоподогреватель',
 '1 водоподогреватель',
 '1 водоподогреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воздухонагреватель',
 '1 воронка',
 '1 воронка',
 '1 воронка',
 '1 воронка',
 '1 вохдухораспределитель',
 '1 вохдухораспределитель',
 '1 вохдухораспределитель',
 '1 вохдухораспределитель',
 '1 вохдухораспределитель',
 '1 вохдухораспределитель',
 '1 вохдухораспределитель',
 '1 вохдухораспределитель',
 '1 вохдухораспределитель',
 '1 вохдухораспределитель',
 '1 вохдухораспределитель',
 '1 вохдухораспределитель',
 '1 вохдухораспределитель',
 '1 вохдухораспределитель',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 врезка',
 '1 вставка',
 '1 вставка',
 '1 вставка',
 '1 вставка',
 '1 вставка',
 '1 вставка',
 '1 вставка',
 '1 вставка',
 '1 вставка',
 '1 вставка',
 '1 вставка',
 '1 вставка',
 '1 вставка',
 '1 вставка',
 '1 вставка',
 '1 втулка',
 '1 вход',
 '1 вход',
 '1 вход',
 '1 вход',
 '1 вход',
 '1 вход',
 '1 въезд',
 '1 въезд',
 '1 въезд',
 '1 въезд',
 '1 выбоина на камень',
 '1 выбоина на камень',
 '1 вызов',
 '1 вызов',
 '1 вызов',
 '1 вызов',
 '1 вызов',
 '1 вызов',
 '1 вызов',
 '1 вызов',
 '1 вызов',
 '1 вызывной аппарат',
 '1 вызывной аппарат',
 '1 вызывной аппарат',
 '1 вызывной аппарат',
 '1 выключатель',
 '1 выключатель',
 '1 выпрямительное устройство',
 '1 выпрямительное устройство',
 '1 выход',
 '1 выход',
 '1 выход',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га',
 '1 га посадок',
 '1 газовый ввод',
 '1 газовый ввод',
 '1 газовый ввод',
 '1 гараж',
 '1 гаситель',
 '1 гвоздь (костыль)',
 '1 гвоздь (костыль)',
 '1 гвоздь (костыль)',
 '1 гвоздь (костыль)',
 '1 гвоздь (костыль)',
 '1 гвоздь (костыль)',
 '1 гвоздь (костыль)',
 '1 гвоздь (костыль)',
 '1 гвоздь (костыль)',
 '1 гвоздь (костыль)',
 '1 гвоздь (костыль)',
 '1 гвоздь (костыль)',
 '1 гидросистема',
 '1 гидросистема',
 '1 гидроцилиндр',
 '1 гидроцилиндр',
 '1 гидроцилиндр',
 '1 гипсовая модель',
 '1 гипсовая модель',
 '1 гипсовая модель',
 '1 гипсовая модель',
 '1 гипсовая модель',
 '1 гипсовая модель',
 '1 гипсовая модель',
 '1 гипсовая модель',
 '1 гипсовая модель',
 '1 гипсовая модель',
 '1 гипсовая модель',
 '1 гипсовая модель',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая отливка',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 гипсовая форма',
 '1 глухое пересечение',
 '1 глухое пересечение',
 '1 гнездо',
 '1 горелка',
 '1 горелка',
 '1 градирня',
 '1 градирня',
 '1 градирня',
 '1 градирня',
 '1 градирня',
 '1 градирня',
 '1 градирня',
 '1 градирня',
 '1 градирня',
 '1 график',
 '1 гребенка',
 '1 гребенка',
 '1 гребенка',
 '1 гребенка',
 '1 гребенка',
 '1 группа',
 '1 группа',
 '1 группа',
 '1 групповой канал',
 '1 грязевик',
 '1 грязевик',
 '1 грязевик',
 '1 грязевик',
 '1 грязевик',
 '1 грязевик',
 '1 грязевик',
 '1 грязевик',
 '1 грязевик',
 '1 грязевик',
 '1 грязевик',
 '1 грязевик',
 '1 грязевик',
 '1 грязевик',
 '1 датчик',
 '1 датчик',
 '1 датчик',
 '1 датчик',
 '1 датчик',
 '1 датчик',
 '1 датчик',
 '1 датчик',
 '1 датчик',
 '1 датчик/устройство',
 '1 датчик/устройство',
 '1 дверь',
 '1 дверь',
 '1 дверь шахты',
 '1 дверь шахты',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 дерево',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 '1 деталь',
 ...]

In [52]:
# Сохраним очищенный справочник
df_final.to_excel('TCH_2001_final.xlsx', index=False)

Новый справочник еще легче и считается за 12 сек.